version: '3'
services:
  record:
    restart: always
    build: ./DanmakuRender
    image: drm:latest
    container_name: recorder
    volumes:
      - /home/xwx/Code/My-Bililive-Recorder/DanmakuRender:/app
      - /home/xwx/Code/My-Bililive-Recorder/configs:/app/configs
