version: '3'
services:
  record:
    restart: always
    user: "1000:1000"
    build: ./DanmakuRender
    image: drm:latest
    container_name: recorder
    volumes:
      - ./DanmakuRender:/app
      - ./configs:/app/configs
      - $HOME/Media/Live:/app/Live
