version: '3'
services:
  record:
    restart: always
    build: ./DanmakuRender
    image: drm:latest
    container_name: recorder
    volumes:
      - ./DanmakuRender:/app
      - ./configs:/app/configs
